version: '3.8'

services:
  # Include MongoDB service that can be enabled/disabled with a condition
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=job-tracking
    restart: unless-stopped
    networks:
      - app-network
    # This service will only start if USE_LOCAL_MONGODB=true
    profiles:
      - local-mongodb

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Support for both MongoDB Atlas and local MongoDB
      - MONGODB_ATLAS_URI=${MONGODB_ATLAS_URI:-}
      - MONGODB_HOST=${MONGODB_HOST:-mongodb}
      - MONGODB_PORT=${MONGODB_PORT:-27017}
      - MONGODB_DATABASE=${MONGODB_DATABASE:-job-tracking}
      - MONGODB_USERNAME=${MONGODB_USERNAME:-admin}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD:-password}
    depends_on:
      # Only depend on MongoDB if using local deployment
      - ${USE_LOCAL_MONGODB:-false}_mongodb
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      # In mono deployment, the backend is available on localhost
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local