app = "job-tracking"
primary_region = "ord" # Chicago - change to your preferred region

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[statics]]
  guest_path = "/app/frontend/build"
  url_prefix = "/"